version: "3"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend_image
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "
            python ghibli/manage.py migrate &&
            python ghibli/manage.py collectstatic --no-input &&
            python ghibli/manage.py runserver 0.0.0.0:8000
             "
    stdin_open: true
    tty: true

  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_volume:/data

volumes:
  static_volume:
  media_volume:
  redis_volume:
